#!/usr/bin/with-contenv bash

# Generate SSH host keys if they don't exist
if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
    ssh-keygen -A
fi

# Start SSH daemon
exec /usr/sbin/sshd -D -f /etc/ssh/sshd_config